services:
  mysql:
    image: docker.io/library/mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: test
       MYSQL_DATABASE: customer_db
       MYSQL_USER: my_user
       MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  postgresql:
    image: docker.io/library/postgres:latest
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  eureka:
    image: "localhost/eurekaserver"
    #build: ./eureka #image build
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=dev
    networks:
      - common
  gateway:
    image: "localhost/gateway"
    ports:
      - "8090:8090"
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
    depends_on: # container başlaması
      - eureka
    healthcheck: # spring başlaması
      test: ["CMD", "curl", "-f", "http://eureka:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
volumes:
  mysql_data:
  postgres_data:
  mongodb_data:

networks:
  common:
    driver: bridge
