spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service.routing
            uri: http://localhost:8081 # customerService isimli servicein url bilgilerini buraya fetch et
            predicates:
              - Path=/api/customers/**
          - id: product-service.routing
            uri: http://localhost:8080
            predicates:
              - Path=/api/products/**
server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
